name: VM Python package

on:
  - push
  - pull_request

jobs:
  bsd:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        platform: 
          - name: freebsd
            version: '13.2'
            host: 
          - name: netbsd
            version: '9.3'
          - name: openbsd
            version: '7.4'
        system-hidapi: ["", "--with-system-hidapi"]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Run in VM
      uses: cross-platform-actions/action@v0.21.1
      env:
        HIDAPI_SYSTEM_HIDAPI: ${{ matrix.system-hidapi == '--with-system-hidapi' && '1' || '0' }}
      with:
        environment_variables: HIDAPI_SYSTEM_HIDAPI
        operating_system: ${{ matrix.platform.name }}
        version: ${{ matrix.platform.version }}
        shell: bash
        copyback: false
        run: |
          set -e

          cd work || true
          cd cython-hidapi || true
          cd cython-hidapi || true
          pwd && ls -l1

          ${{ matrix.platform == 'freebsd' && 'true' || 'false' }} && pkg install -y libiconv pkgconf devel/py-pip ${{ matrix.system-hidapi == '--with-system-hidapi' && 'hidapi' || '' }}
          ${{ matrix.platform == 'netbsd' && 'true' || 'false' }} && /usr/sbin/pkg_add pkgconf libusb1 libiconv py3-pip ${{ matrix.system-hidapi == '--with-system-hidapi' && 'libhidapi' || '' }}
          ${{ matrix.platform == 'openbsd' && 'true' || 'false' }} && pkg_add pkgconf libusb1-- libiconv py3-pip cmake ninja
          ${{ ((matrix.platform == 'openbsd') && (matrix.system-hidapi == '--with-system-hidapi')) && './build_install_hidapi.sh' || 'true' }}

          python -m pip install --upgrade pip
          python -m pip install setuptools tox tox-gh-actions
          pip install -r requirements.txt --upgrade

          pip install .
          tox
