name: VM Python package

on:
  - push
  - pull_request

jobs:
  bsd:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        platform: 
          - name: freebsd
            version: '13.2'
            host: 
          - name: netbsd
            version: '9.3'
          - name: openbsd
            version: '7.4'
        system-hidapi: ["", "--with-system-hidapi"]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Run in VM
      uses: cross-platform-actions/action@v0.21.1
      env:
        HIDAPI_SYSTEM_HIDAPI: ${{ matrix.system-hidapi == '--with-system-hidapi' && '1' || '0' }}
      with:
        environment_variables: HIDAPI_SYSTEM_HIDAPI
        operating_system: ${{ matrix.platform.name }}
        version: ${{ matrix.platform.version }}
        shell: bash
        sync_files: runner-to-vm
        run: |
          set -e

          pwd && ls -l1

          ${{ matrix.platform.name == 'freebsd' && 'sudo pkg install -y libiconv pkgconf lang/python3 lang/python devel/py-pip cmake ninja' || 'true' }}
          ${{ matrix.platform.name == 'netbsd' && 'sudo /usr/sbin/pkg_add pkgconf libusb1 libiconv py3-pip cmake ninja ' || 'true' }}
          ${{ matrix.platform.name == 'openbsd' && 'sudo pkg_add pkgconf libusb1-- libiconv python3 py3-pip cmake ninja' || 'true' }}
          ${{ matrix.system-hidapi == '--with-system-hidapi' && './build_install_hidapi.sh' || 'true' }}

          python -m pip install --upgrade pip
          python -m pip install setuptools tox tox-gh-actions
          pip install -r requirements.txt --upgrade

          pip install .
          python -m tox
