name: VM Python package

on:
  - push
  - pull_request

jobs:
  bsd:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        platform: [freebsd-vm]
        system-hidapi: ["", "--with-system-hidapi"]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Ubuntu HIDAPI
      if:  ${{ (matrix.platform == 'ubuntu-latest') && (matrix.system-hidapi == '--with-system-hidapi') }}
      # the default apt version of libhidapi-dev is too old, need to build the one we know would work
      run: |
        sudo apt install cmake
        mkdir hidapi_build && cd hidapi_build
        cmake -B . -S ../hidapi -DCMAKE_INSTALL_PREFIX=/usr
        make
        sudo make install

    - name: Run in FreeBSD
      if: matrix.platform == 'freebsd-vm'
      uses: vmactions/freebsd-vm@v1
      env:
        HIDAPI_SYSTEM_HIDAPI: ${{ matrix.system-hidapi == '--with-system-hidapi' && '1' || '0' }}
        HIDAPI_WITH_LIBUSB: ${{ matrix.libusb-backend == '--with-libusb' && '1' || '0' }}
      with:
        envs: 'HIDAPI_SYSTEM_HIDAPI HIDAPI_WITH_LIBUSB'
        usesh: true
        prepare: |
          pkg install -y ninja libiconv pkgconf cmake python38 py38-pip
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools tox tox-gh-actions
          pip3 install -r requirements.txt --upgrade

        run: |
          pip3 install .
          tox
