name: VM Python package

on:
  - push
  - pull_request

jobs:
  vm:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        platform: [FreeBSD, NetBSD, OpenBSD]
        system-hidapi: ["", "--with-system-hidapi"]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Run in FreeBSD
      if: ${{ matrix.platform == 'FreeBSD' }}
      uses: vmactions/freebsd-vm@v1
      env:
        HIDAPI_SYSTEM_HIDAPI: ${{ matrix.system-hidapi == '--with-system-hidapi' && '1' || '0' }}
      with:
        envs: 'HIDAPI_SYSTEM_HIDAPI HIDAPI_WITH_LIBUSB'
        usesh: true
        copyback: false
        prepare: |
          set -e

          cd work || true
          cd cython-hidapi || true
          cd cython-hidapi || true
          pwd && ls -l1

          pkg install -y libiconv pkgconf devel/py-pip ${{ matrix.system-hidapi == '--with-system-hidapi' && 'hidapi' || '' }}

          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools tox tox-gh-actions

          pip3 install -r requirements.txt --upgrade

        run: |
          set -e
          cd work || true
          cd cython-hidapi || true
          cd cython-hidapi || true
          pwd && ls -l1

          pip3 install .
          tox

    - name: Run in NetBSD
      if: ${{ matrix.platform == 'NetBSD' }}
      uses: vmactions/netbsd-vm@v1
      env:
        HIDAPI_SYSTEM_HIDAPI: ${{ matrix.system-hidapi == '--with-system-hidapi' && '1' || '0' }}
      with:
        envs: 'HIDAPI_SYSTEM_HIDAPI HIDAPI_WITH_LIBUSB'
        usesh: true
        copyback: false
        prepare: |
          set -e

          cd work || true
          cd cython-hidapi || true
          cd cython-hidapi || true
          pwd && ls -l1

          /usr/sbin/pkg_add pkgconf libusb1 libiconv devel/py-pip ${{ matrix.system-hidapi == '--with-system-hidapi' && 'libhidapi' || '' }}

          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools tox tox-gh-actions

          pip3 install -r requirements.txt --upgrade

        run: |
          set -e
          cd work || true
          cd cython-hidapi || true
          cd cython-hidapi || true
          pwd && ls -l1

          pip3 install .
          tox

    - name: Run in OpenBSD
      # the VM fails to start when this script was developed
      if: ${{ false && matrix.platform == 'OpenBSD' }}
      uses: vmactions/openbsd-vm@v1
      env:
        HIDAPI_SYSTEM_HIDAPI: ${{ matrix.system-hidapi == '--with-system-hidapi' && '1' || '0' }}
      with:
        envs: 'HIDAPI_SYSTEM_HIDAPI HIDAPI_WITH_LIBUSB'
        usesh: true
        copyback: false
        prepare: |
          set -e

          cd work || true
          cd cython-hidapi || true
          cd cython-hidapi || true
          pwd && ls -l1

          pkg_add pkgconf libusb1-- libiconv py-pip cmake ninja
          ${{ matrix.system-hidapi == '--with-system-hidapi' && './build_install_hidapi.sh' || 'true' }}

          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools tox tox-gh-actions

          pip3 install -r requirements.txt --upgrade

        run: |
          set -e
          cd work || true
          cd cython-hidapi || true
          cd cython-hidapi || true
          pwd && ls -l1

          pip3 install .
          tox
